# Generated by Django 5.0 on 2024-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0009_pi_login_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_keys', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fake Keys',
                'verbose_name_plural': 'Fake Keys',
                'ordering': ['-date'],
            },
        ),
    ]
